// Generated by CoffeeScript 1.3.1
(function() {
  var Derringer,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  Derringer = (function(_super) {

    __extends(Derringer, _super);

    Derringer.name = 'Derringer';

    function Derringer() {
      return Derringer.__super__.constructor.apply(this, arguments);
    }

    Derringer.set('mission', 'fight crime');

    Derringer.global(true);

    Derringer.controller('app');

    Derringer.root('app#index');

    return Derringer;

  })(Batman.App);

}).call(this);
