defaults: &defaults
  host: localhost
  port: 5984
  prefix:
  join: "_"

development:
  protocol: http
  suffix: development
  username: CHANGEME
  password: CHANGEME
  <<: *defaults

test:
  protocol: http
  suffix: test
  username: CHANGEME
  password: CHANGEME
  <<: *defaults

production:
  protocol: http # TODO: Write rake task to set up SSL certs so we can change this in couch.example.yml
  suffix:
  username: CHANGEME
  password: CHANGEME
  <<: *defaults
