
defaults: &defaults
  adapter: mysql2
  encoding: utf8
  reconnect: true
  pool: 5
  host: localhost

development:
  database: derringer_development
  username: CHANGEME
  password: CHANGEME
  <<: *defaults

test:
  database: derringer_test
  username: CHANGEME
  password: CHANGEME
  <<: *defaults

production:
  database: derringer_test
  username: CHANGEME
  password: CHANGEME
  <<: *defaults
