class Scan < CouchRest::Model::Base
  unique_id :id # Autogenerated

  property :order_id, Integer
  property :order_code, String
  property :ticket_id, Integer
  property :ticket_code, String
  property :booth, String

  # One half of the timestamps! macro.
  property :created_at, Time, :read_only => true, :protected => true, :auto_validation => false
  set_callback :save, :before do |object|
    write_attribute(:created_at, Time.now)
  end

  # CouchDB Views, functions that the server uses to map (and
  # optionally reduce) records to a result set.
  design do
    view :by_ticket_code
    view :by_order_code
  end

  # Find helpers: find_by_ticket_code exists, but it only retrieves
  # the first record. For us, this is a BAD thing.
  def find_all_by_ticket_code(code)
    by_ticket_code.key(code)
  end
  def find_all_by_order_code(code)
    by_order_code.key(code)
  end

end
